apiVersion: v1
kind: Namespace
metadata:
  name: amq-aa
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-aa-og
  namespace: amq-aa
spec:
  targetNamespaces:
    - amq-aa
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-rhel9
  namespace: amq-aa
spec:
  channel: 7.14.x
  installPlanApproval: Automatic
  name: amq-broker-rhel9
  source: redhat-operators
  sourceNamespace: openshift-marketplace
